version: '3.8'

services:
  api:
    container_name: acordoja-api
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: acordoja-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/dat
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "acordoja"

volumes:
  pgdata: